### ISSUE TITLE
Peer Review by Veyasan Ragulan

### ISSUE THREAD

**Issue by Veyasan1** [DianaShen1224/Forecast-2024-US-election#2]
Summary
A very early render of the final report. The Quarto document hasn't been meaningfully edited yet, and key scripts haven't been worked on yet.
Strong positive points:
Well done analysis on pollster, and outline of poll blueprint
Critical improvements needed:
Make sure you render and upload the pdf of your work. I initially though this project had barely started purely based off the pdf provided, which upon further inspection, was much further behind the quarto file it was based upon.
Complete all scripts that are necessary, and finish the results and discussion section.
Evaluation:
R is appropriately cited - 1/1
Data are appropriately cited - 0/1
Signs of Class Project - 1/1
LLM Usage - 0/1
Title - 1/2
Author, date and repo - 1/2
Abstract - 1/4
Introduction - 1/4
Estimand - 0/1
Data - 2/10
Measurement - 2/4
Model - 6/10
Results - 0/10
Discussion - 0/10
Prose - 4/6
Cross-reference - 0/1
Captions - 0/2
Graphs/Tables - 0/4
Referencing - 0/4
Commits - 2/2
Simulation - 0/4
Tests-Sim - 0/4
Tests-Act - 0/4
Parquet - 0/1
Reproducible workflow - 2/4
Datasheet - 0/10
Misc - 0/3
Estimated overall mark:
24/126
Any other comments:
Great start, I look forward to your final submission! Just make sure the pdf in your repo is up to date.

**Comment by DianaShen1224** [comment]
Thank you for your comment! We have properly cited the data, changed the title to a better one, concise the paragraphs, added more explanation to the detail of the model, added model results, checked the words that shouldn't be used, deleted the title of the graph to remain only the caption of the figure, also updated the caption with more details, change the length of the survey, update references format, delete the space in the filename, use here::here to get the file, and add the scripts.
