### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [DianaShen1224/Forecast-2024-US-election#4]
- R is appropriately cited (1/1)
	- Fine.
- Data are appropriately cited (0/1)
	- Data citation does not resolve - see "fivethirtyeight2024?" on page 2. Whole paper gets zero.
- Class paper (1/1)
	- Fine.
- LLM usage is documented (1/1)
	- Don't forget to update the text file if needed.
- Title (0/2)
	- Remove the subtitle that you have
	- Remove "Based on polling as of 27 October 2024, " from the title
	- Move the rest of the title into a subtitle.
	- Come up with a better title.
- Author, date, and repo (2/2)
	- Fine.
- Abstract (0/4)
	- This is wrong - you didn't use MRP!
- Introduction (2/4)
	- Be more concise.
- Estimand (0/1)
	- Move the estimand paragraph earlier in the introduction so that it is not the final paragraph in the introduction.
- Data (5/10)
	- Don't talk about "the x-axis representing..." etc in the text associated with graphs. Talk about what we see.
	- Figure 5 - it doesn't make sense to keep those old results in your data. They're going to mess with your model. Drop them.
- Measurement (0/4)
	- This is far too general.
- Model (3/10)
	- Too limited and piecemeal explanation.
	- Get someone else in your group to re-read this - not the person who did it. Ask - do you understand what was done here and why?
- Results (5/10)
	- You don't provide the model results.
- Discussion (0/10)
	- Be more concise. Almost terse.
	- Don't yet completed.
- Prose (0/6)
	- Don't use words/phrases that I've asked you not to use - "fill a gap", "delve", "comprehensive" to name a few that jumped out.
- Cross-references (0/1)
	- Cross-references in final paragraph of the introduction not working.
- Captions (1/2)
	- Not enough detail.
- Graphs/tables/etc (1/4)
	- Flip the axis of Figure 3 so that it's legiable.
	- Why do you have both titles and captions e.g. Figure 9?
- Idealized methodology (6/10)
	- The ideas that are here are good but be more concise. 
- Idealized survey (2/4)
	- Why is unfavourable not capitalized?
	- Is this survey too long? Please justify the length.
- Pollster methodology overview and evaluation (5/10)
	- Please use proper paragraphs e.g. the "Established in 1980" one is too long.
	- The difference in the style of writing here compared with elsewhere is pretty stark. Please make sure this is all your own work!
- Referencing (0/4)
	- Citations not working. 
	- You are going to have double brackets around your in-text citations because you're using (@my_cite) instead of [@my_cite]
	- Fix capitalization e.g. Q&a: 
	- Fix consistency e.g. "Times, The New York" "The New York Times"
- Commits (2/2)
	- Fine.
- Sketches (0/2)
	- Not yet done.
- Simulation (0/4)
	- Not yet done.
- Tests-simulation (0/4)
	- Not yet done.
- Tests-actual (0/4)
	- Not yet done.
- Parquet (1/1)
	- Fine.
- Reproducible workflow (0/4)
	- README title needs a little more detail.
	- Why are there spaces in the filenames? https://github.com/DianaShen1224/Forecast-2024-US-election/blob/main/scripts/02-download_data.R
	- Spaces in filename and ~ happens throughout. Just change them to be in relation to the Rproj and use here::here() if necessary - see the starter folder example.
	- Some scripts still need to be updated and have  [...UPDATE THIS...] in them.
- Miscellaneous (1/3)
	- You implemented an attention check in your survey!

**Comment by DianaShen1224** [comment]
Thank you so much professor for your comment! We have properly cited the data, changed the title to a better one, concise the paragraphs, added more explanation to the detail of the model, added model results, checked the words that shouldn't be used, deleted the title of the graph to remain only the caption of the figure, also updated the caption with more details, change the length of the survey, update references format, delete the space in the filename, use here::here to get the file,  and add the scripts.
